# Generated by Django 3.0.7 on 2020-06-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200626_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_USA',
            new_name='fess_in_USA',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fees_in_world',
            new_name='fess_in_world',
        ),
    ]
