# Generated by Django 3.0.7 on 2020-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(null=True, verbose_name='Текст ответа')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта спросившего')),
                ('name', models.CharField(max_length=100, verbose_name='Имя спросившего')),
                ('check', models.BooleanField(default=False, verbose_name='Проверено/В проверке')),
            ],
        ),
    ]
