# Generated by Django 3.0.7 on 2020-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200824_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blockLinkBorderColor',
            field=models.CharField(default=None, max_length=50, verbose_name='Цвет границы кнопки (ссылки)'),
        ),
        migrations.AddField(
            model_name='block',
            name='blockLinkTextColor',
            field=models.CharField(default=None, max_length=50, verbose_name='Цвет текста кнопки (ссылки)'),
        ),
    ]
